[workspace]
authors = ["Xingxin HE <xingxin.he@connect.ust.hk>"]
channels = ["robostack-humble", "conda-forge"]
name = "pixi_realsense_ros2"
platforms = ["linux-64"]
version = "0.1.0"

[activation]
scripts = [
    "scripts/set_env.sh",
]



[activation.env]
CRISP_CONFIG_PATH = "./crisp_configs"
ROS_DOMAIN_ID = "100"
RMW_IMPLEMENTATION = "rmw_zenoh_cpp"
ZENOH_SESSION_CONFIG_URI="./configs/zenoh_client.json5"


[tasks]
camera = "ros2 launch realsense2_camera rs_launch.py camera_namespace:=/ camera_name:=camera enable_depth:=false rgb_camera.color_profile:=640x480x30"
test-image = "python one_camera.py"
camera-dual = "ros2 launch realsense2_camera rs_multi_camera_launch.py camera_namespace1:=/ camera_name1:=wrist serial_no1:=_342522074350 camera_namespace2:=/ camera_name2:=third_person serial_no2:=_347622071856 initial_reset1:=true initial_reset2:=true enable_depth1:=false enable_depth2:=false rgb_camera.color_profile1:=640x480x30 rgb_camera.color_profile2:=640x480x30"
test-image-dual = "python two_cameras.py"
camera-triple = "bash scripts/launch_three_cameras.sh"
test-image-triple = "python three_cameras.py"
list-cameras = "python list_cameras.py"
clean = "pkill -f realsense2_camera_node"

[dependencies]
ros-humble-ros-base = "=0.10.0"
ros-humble-librealsense2 = "=2.55.1"
ros-humble-realsense2-camera = "=4.55.1"
ros-humble-realsense2-camera-msgs = "=4.55.1"
ros-humble-realsense2-description = "=4.55.1"
python = ">=3.11.14,<3.12"
matplotlib = ">=3.10.8,<4"
ros-humble-compressed-image-transport = "=2.5.3"
ros-humble-rmw-zenoh-cpp = "=0.1.2"
ros2-distro-mutex = "=0.7.0"

[pypi-dependencies]
crisp-python = ">=3.4.0, <4"
pyrealsense2 = ">=2.56.5.9235, <3"
