[workspace]
authors = ["Xingxin HE <xingxin.he@connect.ust.hk>"]
channels = ["robostack-jazzy", "conda-forge"]
name = "pixi_realsense_ros2"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
libc = { family = "glibc", version = "2.39" }

[activation]
scripts = [
    "scripts/set_env.sh",
]



[activation.env]
CRISP_CONFIG_PATH = "./crisp_configs"
ROS_DOMAIN_ID = "100"
RMW_IMPLEMENTATION = "rmw_cyclonedds_cpp"  # or rmw_zenoh_cpp
ZENOH_SESSION_CONFIG_URI = "./zenoh_client.json5"
CYCLONEDDS_URI = "file://$PIXI_PROJECT_ROOT/cyclone_config.xml"

[tasks]
camera = "ros2 launch realsense2_camera rs_launch.py camera_namespace:=/ camera_name:=camera enable_depth:=false rgb_camera.color_profile:=640x480x30"
camera-dual = "bash scripts/launch_two_cameras.sh"
camera-triple = "bash scripts/launch_three_cameras.sh"
clean = "pkill -f realsense2_camera_node"
zenoh-router = "ros2 run rmw_zenoh_cpp rmw_zenohd"
[dependencies]
ros-jazzy-ros-base = "*"
ros-jazzy-librealsense2 = ">=2.57.7,<2.57.8"
ros-jazzy-realsense2-camera = ">=4.57.7,<4.57.8"
ros-jazzy-realsense2-camera-msgs = ">=4.57.7,<4.57.8"
ros-jazzy-realsense2-description = ">=4.57.7,<4.57.8"
python = ">=3.12,<3.13"
matplotlib = ">=3.10.8,<4"
numpy = ">=2,<=2.3.0"
ros-jazzy-compressed-image-transport = "*"
ros-jazzy-rmw-zenoh-cpp = "*"
ros2-distro-mutex = ">=0.15.0,<0.16"
ros-jazzy-rqt-image-view = ">=1.3.0,<2"
ros-jazzy-rqt-gui = ">=1.6.3,<2"

[pypi-dependencies]
crisp-python = ">=3.4.0, <4"
pyrealsense2 = ">=2.56.5.9235, <3"
